name: task_manager
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  animate_do: ^2.0.0
  flutter_animated_dialog: ^2.0.1
  pull_to_refresh: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  sqflite: ^2.0.0+3
  flutter_local_notifications: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/user.json

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Medium.ttf
